spring:
  application:
    name: tiger_gateway
  cloud:
    gateway:
      globalfilters:
        - name: GlobalsFilter
          args:
            blacklist: 192.168.1.100,192.168.1.101
      routes:
        - id: tiger_admin
          uri: http://127.0.0.1:8400
          predicates:
            - Path=/admin095ce/**
          filters:
            - name: RouteFilterFactory
              args:
                requestHeaderTokenName: token
                adminHeaderTokenName: admin_token
                enabled: true

server:
  port: 8300

