spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java, src/main/resources
      exclude: WEB-INF,META-INF
      log-condition-evaluation-delta: false
  application:
    name: tigerApp

server:
  port: 8500

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8100/tiger_eureka/eureka/
  server:
    enable-self-preservation: false

#负载均衡
tigerApp:
  ribbon:
    eureka:
      enabled: true
    ConnectTimeout: 3000
    ReadTimeout: 3000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    #可以根据负载策略自行实现逻辑
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#降级熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
  threadpool:
    default:
      coreSize: 10
      maxQueueSize: -1

#监控
turbine:
  aggregator:
    clusterConfig: default
  appConfig: tigerApp
  clusterNameExpression: new String("default")

xxl.job:
  admin:
    addresses: http://127.0.0.1:8080/xxl-job-admin
  accessToken: default_token
  executor:
    appName: tigerAppGame
    address:
    ip:
    port:
    logpath: /Users/huangsanming/Downloads/
    logretentiondays: 1