server:
  port: 8100
  servlet:
    context-path: /tiger_eureka

spring:
  application:
    name: tiger_eureka

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    healthcheck:
      enabled: true
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/${spring.application.name}/eureka/
  server:
    enable-self-preservation: true

