server:
  port: 8103

spring:
  application:
    name: tigerEurekaClusterB

eureka:
  instance:
    hostname: ClusterB
  client:
    healthcheck:
      enabled: true
    #由于注册中心的职责就是维护服务实例，它并不需要去检索服务
    fetch-registry: false
    #不向注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://Cluster:8100/eureka/,http://ClusterA:8103/eureka/

